import {
  CalendarIcon,
  ChevronRight,
  Command,
  CropIcon,
  Laptop,
  LayoutDashboard,
  LogOut,
  Menu,
  Moon,
  PencilIcon,
  Settings,
  SunMedium,
  Trash2Icon,
  User,
} from "lucide-react";

export const Icons = {
  logo: Command,
  menu: Menu,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  chevronRight: ChevronRight,
  user: User,
  settings: Settings,
  dashboard: LayoutDashboard,
  logOut: LogOut,
  crop: CropIcon,
  thrash: Trash2Icon,
  calendar: CalendarIcon,
  pencil: PencilIcon,
};
